### ISSUE TITLE
[Enhancement] Allow certain aspects of the mod to be toggleable

### ISSUE THREAD

**Issue by payphone101** [SmushyTaco/Expanded-Crossbow-Enchanting#1]
Hi, is there a way to be able to blacklist some enchantments so that they aren't going to be used? For example we use the datapack `Dungeons and Taverns` which adds `Ghasted` (makes arrows explode on impact) and I'd like to have `Multishot` on it but not `Infinity`.

**Comment by SmushyTaco** [comment]
This isn't possible or planned, sorry.
